### ISSUE TITLE
Adapter don t  start..

### ISSUE THREAD

**Issue by Ilovegym66** [iobroker-community-adapters/ioBroker.wifilight#19]
actual Version on Git don t start:
`

host.Masterbroker | 2019-08-06 14:09:43.195 | error | instance system.adapter.wifilight-community.0 terminated with code 0 (OK)
-- | -- | -- | --
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at Socket.that.objects.getObjectView  (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2732:25)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:848:21
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at safeCallback  (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:188:13)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1297:9
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at main (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:917:54)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at WifiLight.run (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:170:10)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at WifiLight.createDevice (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:197:19)
Caught | 2019-08-06 14:09:43.195 | error | by controller[0]:     at CDevice.getFullId  (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1113:20)
Caught | 2019-08-06 14:09:43.194 | error | by controller[0]:     at dcs (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:304:33)
Caught | 2019-08-06 14:09:43.194 | error | by controller[0]: TypeError: Cannot read property '0' of undefined
wifilight-community.0 | 2019-08-06 14:09:43.186 | info | terminating
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at Socket.onack (/opt/iobroker/node_modules/socket.io-client/lib/socket.js:312:9)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at Socket.that.objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:2732:25)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:848:21
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at safeCallback (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:188:13)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1297:9
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at main (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:917:54)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at WifiLight.run (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:170:10)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at WifiLight.createDevice (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:197:19)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at CDevice.getFullId (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1113:20)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | at dcs (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:304:33)
wifilight-community.0 | 2019-08-06 14:09:43.182 | error | TypeError: Cannot read property '0' of undefined
wifilight-community.0 | 2019-08-06 14:09:43.181 | error | uncaught exception: Cannot read property '0' of undefined
wifilight-community.0 | 2019-08-06 14:09:43.099 | info | starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.wifilight-community, node: v8.16.0
host.Masterbroker | 2019-08-06 14:09:42.764 | info | instance system.adapter.wifilight-community.0 started with pid 30098
host.Masterbroker | 2019-08-06 14:09:42.752 | info | object change system.adapter.wifilight-community.0

`

**Comment by Ilovegym66** [comment]
any news about? no changes with node 10.16.3, and js-controller 2.0.35.

**Comment by Ilovegym66** [comment]
fixed with 1.1.0
