### ISSUE TITLE
Colors.rgb2hsv is not a function

### ISSUE THREAD

**Issue by mcuiobroker** [iobroker-community-adapters/ioBroker.wifilight#407]
```
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | instance system.adapter.wifilight.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at processImmediate (node:internal/timers:483:21)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11200:62)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.wifilight/lib/dontBeSoSoef.js:1113:21)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at Object.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:150:12)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at WifiLight.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:272:18)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: at WifiLight.bri (/opt/iobroker/node_modules/iobroker.wifilight/main.js:751:24)
host.iobrokerPROD | 2024-08-14 19:18:46.212 | error | Caught by controller[0]: TypeError: Colors.rgb2hsv is not a function
wifilight.0 | 2024-08-14 19:18:45.971 | error | Colors.rgb2hsv is not a function
wifilight.0 | 2024-08-14 19:18:45.971 | error | TypeError: Colors.rgb2hsv is not a function at WifiLight.bri (/opt/iobroker/node_modules/iobroker.wifilight/main.js:751:24) at WifiLight.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:272:18) at Object.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:150:12) at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.wifilight/lib/dontBeSoSoef.js:1113:21) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11200:62) at processImmediate (node:internal/timers:483:21)
wifilight.0 | 2024-08-14 19:18:45.971 | error | uncaught exception: Colors.rgb2hsv is not a function
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | instance system.adapter.wifilight.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at processImmediate (node:internal/timers:483:21)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11200:62)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.wifilight/lib/dontBeSoSoef.js:1113:21)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at Object.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:150:12)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at WifiLight.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:272:18)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: at WifiLight.bri (/opt/iobroker/node_modules/iobroker.wifilight/main.js:751:24)
host.iobrokerPROD | 2024-08-14 19:18:30.709 | error | Caught by controller[0]: TypeError: Colors.rgb2hsv is not a function
wifilight.0 | 2024-08-14 19:18:30.475 | error | Colors.rgb2hsv is not a function
wifilight.0 | 2024-08-14 19:18:30.475 | error | TypeError: Colors.rgb2hsv is not a function at WifiLight.bri (/opt/iobroker/node_modules/iobroker.wifilight/main.js:751:24) at WifiLight.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:272:18) at Object.onStateChange (/opt/iobroker/node_modules/iobroker.wifilight/main.js:150:12) at Object.options.stateChange (/opt/iobroker/node_modules/iobroker.wifilight/lib/dontBeSoSoef.js:1113:21) at Immediate.<anonymous> (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/src/lib/adapter/adapter.ts:11200:62) at processImmediate (node:internal/timers:483:21)
```
**Versions:**  
 - Adapter version: 1.3.2
 - JS-Controller version: 5.0.19
 - Node version: <node-version> 20.16.0
 - Operating system: debian

**Comment by Ilovegym66** [comment]
Ist mir heute auch aufgefallen..

**Comment by reloxx13** [comment]
me2

**Comment by Ilovegym66** [comment]
@GermanBluefox  any news ? the Adapter crashs, if the command object is set with r:0, g:0, b:0, on:true, transition:30

otherwise we have to roll back to version 1.2.1, this have the faulty states but don't crashs.. :(

**Comment by GermanBluefox** [comment]
I really do not understand, why `function` is not a function. without hardware is to hard to reproduce this error.
![image](https://github.com/user-attachments/assets/0043bcfc-8f44-48f5-95a0-798114b51254)

On other side, there are at least 3 people with hardware and no one could even look into adapter. Very sad

**Comment by mcuiobroker** [comment]
What should I do?

**Comment by GermanBluefox** [comment]
> What should I do?

For now: just test the new version 1.3.3
For future, I am recording the video: "How to debug the ioBroker adapter to help the developer". It is possible with ease without any additional tools. Just chrome and CLI (shell)

https://medium.com/@paul_irish/debugging-node-js-nightlies-with-chrome-devtools-7c4a1b95ae27

```
cd /opt/iobroker
iob stop wifilight
node --inspect-brk=0.0.0.0 node_modules/iobroker.wifilight/main.js --debug
```
Add into chrome://inspect your raspberry pi
![image](https://github.com/user-attachments/assets/17ebefcb-5fc0-4967-a175-31950191c65d)

and then after 10-30 seconds the inspect will appear in the list:
![image](https://github.com/user-attachments/assets/afa3e95a-ad1a-4075-90a2-f2a83cb80cdd)

after that set the breakpoint to line main.js:751 and generate the error
Show the developer scopes and in this particular case the value of `rgb2hsv`

**Comment by mcuiobroker** [comment]
When I start/restart the Instance all Devices set to On=true

**Comment by GermanBluefox** [comment]
> When I start/restart the Instance all Devices set to On=true all devices, which are reachable.
> 
> When devices will power off for save energy and power will be turned on, then the device is not reachable further on. So I have to restart the instance. It should rescan after a time (10s)?

Sorry I could not understand you. May be "deutsch"?

**Comment by Apollon77** [comment]
Mich wundert das dort Colors.rgb2hsv steht ... der Direktimport würde and er Stelle an sich ne andere Meldung verursachen ... das ist mega komisch ... @mcuiobroker Wirklich sicher das die neue version korrekt installiert ist? Korrekter host bei multihost und so? Bitte mal volles Debug log posten bis zu dem Fehler

**Comment by Apollon77** [comment]
@mcuiobroker Please check the most recent verison 1.3.3

**Comment by mcuiobroker** [comment]
@GermanBluefox 
Wenn ich die Instanz starte oder neu starte  werden alle erreichbaren Geräte eingeschaltet. Die Lichter gehen an. Die zugehörigen on-DPs werden auf true gesetzt -> on=true

Der obige Fehler kommt nicht mehr.

Um Energie zu sparen sind einige LED an einem Power-Switch, so dass sie nicht permanent Strom ziehen. Dort sind auch noch andere Geräte (keine wifilight) mit involviert.
Sind diese Geräte bei Instanzstart nicht an werden sie als reachable false erkannt -> ok
Schalte ich nun den Power-Switch wieder ein, so sind die Wifilight, die eben noch aus waren jetzt an. 
Jetzt sollten die wifilight Geräte ja von iobroker erreichbar sein, sind sie aber nicht.

Damit ich sie über iobroker steuern kann, muss ich  die Instanz neu starten.  Sie werden nicht automatisch erkannt (erst nach restart der Instanz) und somit deren reachable auf true gesetzt.

Debug-Log kommt, wenn ich wieder die Möglichkeit habe. Zurzeit Mobil.

**Comment by mcuiobroker** [comment]
@Apollon77 Der obige Fehler wurde ja behoben mit 1.3.3. Es ist nur ein anderes Problem entstanden. Habe es einen Post höher beschrieben.
Zurzeit kann ich kein Log schicken.

**Comment by GermanBluefox** [comment]
> Wenn ich die Instanz starte oder neu starte werden alle erreichbaren Geräte eingeschaltet. Die Lichter gehen an. Die zugehörigen on-DPs werden auf true gesetzt -> on=true

Ist dieser Fehler erst mit 1.3.x gekommen oder war der auch in 1.2.2 drin?

> Um Energie zu sparen sind einige LED an einem Power-Switch, so dass sie nicht permanent Strom ziehen. Dort sind auch noch andere Geräte (keine wifilight) mit involviert. Sind diese Geräte bei Instanzstart nicht an werden sie als reachable false erkannt -> ok Schalte ich nun den Power-Switch wieder ein, so sind die Wifilight, die eben noch aus waren jetzt an. Jetzt sollten die wifilight Geräte ja von iobroker erreichbar sein, sind sie aber nicht.
> 
> Damit ich sie über iobroker steuern kann, muss ich die Instanz neu starten. Sie werden nicht automatisch erkannt (erst nach restart der Instanz) und somit deren reachable auf true gesetzt.
> 
> Ist das Gerät bei Instanzstart an und ich schalte es dann durch Power-Switch ab, so wird der reachable nicht geändert, er bleibt weiterhin auf true. Es findet also keine korrekte reachable-Prüfung statt?

Ist dieser Fehler erst mit 1.3.x gekommen oder war der auch in 1.2.2 drin?


Da der Adapter schlecht geschrieben ist (globale variablen, nicht mehr unterstütze Pakete) für mich sehr kompliziert ohne Hardware den Adapter zu pflegen.

**Comment by mcuiobroker** [comment]
Ist erst mit 1.3.3 gekommen.
Soll ich Dir die Hardware zuschicken? Hab aber nur eine Variante (MagicHome) Wifi LED Controller, kein MiLight.

**Comment by mcuiobroker** [comment]
Geräte suchen in der Instanz-Konfiguration -> Fehler
```

2024-09-03 19:25:24.132 - error: wifilight.0 (63730) uncaught exception: result.include is not a function
--
2024-09-03 19:25:24.133 - error: wifilight.0 (63730) TypeError: result.include is not a function
at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.133 - error: wifilight.0 (63730) result.include is not a function
2024-09-03 19:25:24.137 - error: wifilight.0 (63730) uncaught exception: result.include is not a function
2024-09-03 19:25:24.137 - error: wifilight.0 (63730) TypeError: result.include is not a function
at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.137 - error: wifilight.0 (63730) result.include is not a function
2024-09-03 19:25:24.138 - error: wifilight.0 (63730) uncaught exception: result.include is not a function
2024-09-03 19:25:24.138 - error: wifilight.0 (63730) TypeError: result.include is not a function
at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.139 - error: wifilight.0 (63730) result.include is not a function
2024-09-03 19:25:24.139 - error: wifilight.0 (63730) uncaught exception: result.include is not a function
2024-09-03 19:25:24.139 - error: wifilight.0 (63730) TypeError: result.include is not a function
at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
at Socket.emit (node:events:519:28)
at Socket.emit (node:domain:488:12)
at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.139 - error: wifilight.0 (63730) result.include is not a function
2024-09-03 19:25:24.141 - info: wifilight.0 (63730) terminating
2024-09-03 19:25:24.141 - warn: wifilight.0 (63730) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[0]: TypeError: result.include is not a function
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[0]: at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[0]: at Socket.emit (node:events:519:28)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[0]: at Socket.emit (node:domain:488:12)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[0]: at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[1]: TypeError: result.include is not a function
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[1]: at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[1]: at Socket.emit (node:events:519:28)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[1]: at Socket.emit (node:domain:488:12)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[1]: at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[2]: TypeError: result.include is not a function
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[2]: at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[2]: at Socket.emit (node:events:519:28)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[2]: at Socket.emit (node:domain:488:12)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[2]: at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[3]: TypeError: result.include is not a function
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[3]: at Socket. (/opt/iobroker/node_modules/iobroker.wifilight/lib/discovery.js:31:20)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[3]: at Socket.emit (node:events:519:28)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[3]: at Socket.emit (node:domain:488:12)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD Caught by controller[3]: at UDP.onMessage (node:dgram:946:8)
2024-09-03 19:25:24.436 - error: host.iobrokerPROD instance system.adapter.wifilight.0 terminated with code 1 (JS_CONTROLLER_STOPPED)

```

**Comment by Ilovegym66** [comment]
fixed in 1.3.5, well done!

**Comment by mcuiobroker** [comment]
Bleibt noch das Problem mit den "destroy" Clients. Einmal gelöschte Clients / IPs werden nach Einschalten (Power-Switch) nicht erfasst. -> Man muss die Instanz neu starten.

**Comment by GermanBluefox** [comment]
> EDIT: Es werden die LEDs jetzt nicht mehr geschaltet.

Ich habe wirklich nichts diesbezüglich getan

**Comment by Ilovegym66** [comment]
bei mir funktioniert alles bestens, mit 1.3.5. 
Sogar, wenn mit der App geschaltet wird, wird der Status von PowerON nach max 30sec aktualisiert, das gabs vorher ja nie.
Hier meine Devices (gibt ja verschiedene Hardware) mit den Ports:
![Screenshot 2024-09-05 at 08 45 52](https://github.com/user-attachments/assets/b26670a1-a1db-4f13-9eb3-26ed033c9334)

**Comment by mcuiobroker** [comment]
Habe jetzt nochmal von 1.2.2 NPM-Update gemacht. Jetzt läuft es. Komisch.
Problem ist aber nachwievor, dass man die Instanz neu starten muss für die devices, die man stromlos geschaltet hatte und wieder einschaltet.
Und der ack wird anscheinend nicht immer gesetzt?
![image](https://github.com/user-attachments/assets/55aff9a9-aedf-455b-8bc2-6ef55427ae2f)

**Comment by GermanBluefox** [comment]
Ich habe wifilight ziemlich umgeschrieben.
Bitte v2.0.0 ausprobieren

**Comment by mcuiobroker** [comment]
Da kommt dann dies. Adapter bleibt rot
```

2024-09-05 15:19:01.920 - info: host.iobrokerPROD instance system.adapter.wifilight.0 started with pid 704570
--
2024-09-05 15:19:02.371 - info: wifilight.0 (704570) starting. Version 2.0.0 (non-npm: iobroker-community-adapters/ioBroker.wifilight) in /opt/iobroker/node_modules/iobroker.wifilight, node: v20.17.0, js-controller: 5.0.19
2024-09-05 15:19:02.487 - error: wifilight.0 (704570) uncaught exception: akt.cmd.eq is not a function
2024-09-05 15:19:02.487 - error: wifilight.0 (704570) TypeError: akt.cmd.eq is not a function
at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
at listOnTimeout (node:internal/timers:581:17)
at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:02.487 - error: wifilight.0 (704570) akt.cmd.eq is not a function
2024-09-05 15:19:02.493 - error: wifilight.0 (704570) uncaught exception: akt.cmd.eq is not a function
2024-09-05 15:19:02.493 - error: wifilight.0 (704570) TypeError: akt.cmd.eq is not a function
at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
at listOnTimeout (node:internal/timers:581:17)
at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:02.493 - error: wifilight.0 (704570) akt.cmd.eq is not a function
2024-09-05 15:19:02.494 - info: wifilight.0 (704570) terminating
2024-09-05 15:19:02.494 - warn: wifilight.0 (704570) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[0]: TypeError: akt.cmd.eq is not a function
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[0]: at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[0]: at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[0]: at listOnTimeout (node:internal/timers:581:17)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[0]: at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[1]: TypeError: akt.cmd.eq is not a function
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[1]: at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[1]: at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[1]: at listOnTimeout (node:internal/timers:581:17)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD Caught by controller[1]: at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:02.727 - error: host.iobrokerPROD instance system.adapter.wifilight.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-09-05 15:19:02.727 - info: host.iobrokerPROD Restart adapter system.adapter.wifilight.0 because enabled
2024-09-05 15:19:32.762 - info: host.iobrokerPROD instance system.adapter.wifilight.0 started with pid 704703
2024-09-05 15:19:33.209 - info: wifilight.0 (704703) starting. Version 2.0.0 (non-npm: iobroker-community-adapters/ioBroker.wifilight) in /opt/iobroker/node_modules/iobroker.wifilight, node: v20.17.0, js-controller: 5.0.19
2024-09-05 15:19:33.354 - error: wifilight.0 (704703) uncaught exception: akt.cmd.eq is not a function
2024-09-05 15:19:33.354 - error: wifilight.0 (704703) TypeError: akt.cmd.eq is not a function
at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
at listOnTimeout (node:internal/timers:581:17)
at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:33.355 - error: wifilight.0 (704703) akt.cmd.eq is not a function
2024-09-05 15:19:33.360 - info: wifilight.0 (704703) terminating
2024-09-05 15:19:33.360 - warn: wifilight.0 (704703) Terminated (UNCAUGHT_EXCEPTION): Without reason
2024-09-05 15:19:33.558 - error: host.iobrokerPROD Caught by controller[0]: TypeError: akt.cmd.eq is not a function
2024-09-05 15:19:33.559 - error: host.iobrokerPROD Caught by controller[0]: at WifiLight.exec (/opt/iobroker/node_modules/iobroker.wifilight/main.js:784:52)
2024-09-05 15:19:33.559 - error: host.iobrokerPROD Caught by controller[0]: at Timeout._onTimeout (/opt/iobroker/node_modules/iobroker.wifilight/main.js:791:55)
2024-09-05 15:19:33.559 - error: host.iobrokerPROD Caught by controller[0]: at listOnTimeout (node:internal/timers:581:17)
2024-09-05 15:19:33.559 - error: host.iobrokerPROD Caught by controller[0]: at processTimers (node:internal/timers:519:7)
2024-09-05 15:19:33.559 - error: host.iobrokerPROD instance system.adapter.wifilight.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
2024-09-05 15:19:33.559 - info: host.iobrokerPROD Restart adapter system.adapter.wifilight.0 because enabled


```

**Comment by Ilovegym66** [comment]
yes, with V2.0 the same errors: akt.cmd.eq is not a function - back to V1.3.5, everything is fine. (productive system)

**Comment by GermanBluefox** [comment]
Ich habe das gerät jetzt simuliert und konnte den Fehler reproduzieren.
Jetzt sollte laufen

**Comment by Ilovegym66** [comment]
Super, vielen Dank, mit 2.0.1 funktioniert jetzt alles. Beim starten des Adapters hatte ich 3 Devices als offline angezeigt bekommen, wobei davon nur wirklich eins offline war (lt. App). Ich habe die Pollzeit bei den anderen beiden Devices von 30 auf 60 erhoeht, den Adapter neu gestartet, jetzt werden alle (bis auf das eine, was wirklich offline ist) richtig angezeigt.
Habe soweit alle Funktionen getestet, keine Fehler mehr. 
Vielen Vielen Vielen Dank !

**Comment by mcuiobroker** [comment]
Bei mir nicht, gleiches Verhalten, wie sonst auch. Ist die Instanz gestartet und einige Geräte sind stromlos, werden diese auch nach Minuten nicht erkannt, wenn man dort den Strom einschaltet.
Auch ein manueller Refresh funktioniert nicht. 
Erst nach Restart von der Instanz sind die Geräte als reachable erkannt und können geschaltet werden.

**Comment by mcm1957** [comment]
@mcuiobroker 
Da as Issue schin geschlossen wurde und eigentlich "Colors.rgb2hsv is not a function" betrifft, wär es ev. sinnvoll ein neues Issue mit deinem Problem anzulgen - incl der bei dir im Einsatz befindlichen Versionen und einem DEBUG Log. Alternativ kannst du natürlich auch warten ob sich @GermanBluefox hier nochmals dazu meldet.

**Comment by mcuiobroker** [comment]
Kann ich machen, aber ich hatte das Problem auch schon 3x hier erwähnt. Er kennt es.

**Comment by mcm1957** [comment]
Jep - deswegen hab ich auch geschrieben dass du auch gerne auf eine Reaktion von BF hier warten kannst. Wenn nix in den nächsten Tagen kommt, dann schlage ich eher ein neues Issue vor, da die geclosten später niemand mehr durchsieht. Hoff auch dein Problem wird rasch gefixed mit dem rewrite des Museums Adapter hat BF ja schon mal tolle Arbeit geleistet und das Ding wartbar gemacht. DANKE @GermanBluefox
