### ISSUE TITLE
Typ AK001-ZJ210 wird nicht unterstützt ?

### ISSUE THREAD

**Issue by jogibear9988** [iobroker-community-adapters/ioBroker.wifilight#9]
_From @Ridesa on November 7, 2018 16:5_

Hab mir das Set hier gekauft https://www.amazon.de/gp/product/B07BLZCPPG/ref=oh_aui_detailpage_o04_s00?ie=UTF8&psc=1

bekomme da folgende Fehlermeldung

wifilight.0 | 2018-11-07 17:01:37.812 | error | wrong device type. not yet supported!
-- | -- | -- | --
wifilight.0 | 2018-11-07 17:01:37.810 | error | config.device.type "" (AK001-ZJ210) is not a known device type. Skipping this device! Known types are: LW12, LD382A, LD382, UFO, MiLight, MiLightRGB, MiLightW

_Copied from original issue: soef/ioBroker.wifilight#24_

**Comment by jogibear9988** [comment]
_From @ak-media on November 24, 2018 21:14_

Da hänge ich mich mal an. Bei mir funktioniert es auch nicht. Schön eine Lösung in Sicht?

**Comment by jogibear9988** [comment]
_From @ak-media on November 25, 2018 8:59_

Min Log wirft folgendes aus:


wifilight.0 | 2018-11-25 09:55:13.957 | error | wrong device type.  not yet supported!
-- | -- | -- | --
wifilight.0 | 2018-11-25 09:55:13.957 | error | Known types are: LW12, LD382A, LD382, UFO, MiLight, MiLightRGB, MiLightW
wifilight.0 | 2018-11-25 09:55:13.957 | error | config.device.type  (AK001-ZJ210) is not a known device type. Skipping this device!
wifilight.0 | 2018-11-25 09:55:13.943 | info | starting. Version 0.2.0 in /Applications/ioB/node_modules/iobroker.wifilight, node: v10.13.0

**Comment by jogibear9988** [comment]
_From @Dome2075 on January 1, 2019 11:43_

Bin auch betoffen!!

Bitte Supporten

**Comment by TobiasF1986** [comment]
Ich habe den gleichen Controller und in der Adaptereinstellung bei den gefundenen Geräten als Typ LD382 eingetragen. So klappt es scheinbar halbwegs.

**Comment by darkson95** [comment]
> Ich habe den gleichen Controller und in der Adaptereinstellung bei den gefundenen Geräten als Typ LD382 eingetragen. So klappt es scheinbar halbwegs.

Dieser Workaround hat bei mir funktioniert. Vielen Dank!

**Comment by Gerrni** [comment]
Ich nutze dieses Paket, scheint ebenfalls der Controller ZJ210 zu sein allerdings hat der hier genannte Workarround bei mir nicht geholfen. Oder ist das noch wieder ein anderer Typ? Mit Typ "LD382" bleibt der Adapter rot. Ohne Typ Angabe ist er grün.

Allerdings werden keine Objekte angelegt.

https://www.amazon.de/gp/product/B07F9RYKVV/ref=ppx_yo_dt_b_search_asin_title?ie=UTF8&psc=1

**Comment by tolas9** [comment]
Hat jemand eine Lösung

**Comment by tolas9** [comment]
Moin Moin, gibt es hierfür schon eine lösung? bei mir geht auch nichts

**Comment by Ilovegym66** [comment]
LD382A eintragen, dann gehts.

**Comment by Gerrni** [comment]
Mit LD382A bleibt der Adapter rot.

**Comment by Xyolyp** [comment]
Ich habe auch eine AK001-ZJ210 und bekomme bei den Typen LD382A und LD382 die untenstehenden Logmeldungen.
`2019-11-20 14:02:06.848  - [32minfo[39m: host.ioBroker-Pi instance system.adapter.wifilight-community.0 started with pid 3677
2019-11-20 14:02:09.336  - [32minfo[39m: wifilight-community.0 (3677) starting. Version 0.2.1 in /opt/iobroker/node_modules/iobroker.wifilight-community, node: v10.17.0
2019-11-20 14:02:09.512  - [31merror[39m: wifilight-community.0 (3677) uncaught exception: Cannot read property '0' of undefined
2019-11-20 14:02:09.513  - [31merror[39m: wifilight-community.0 (3677) TypeError: Cannot read property '0' of undefined
    at dcs (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:304:33)
    at CDevice.getFullId (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1113:20)
    at WifiLight.createDevice (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:197:19)
    at WifiLight.run (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:170:10)
    at main (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:917:54)
    at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1297:9
    at safeCallback (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:188:13)
    at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:848:21
    at objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3499:25)
    at client.evalsha (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInRedis.js:2243:17)
2019-11-20 14:02:09.524  - [32minfo[39m: wifilight-community.0 (3677) terminating
2019-11-20 14:02:09.528  - [32minfo[39m: wifilight-community.0 (3677) Terminated (NO_ERROR): Without reason
2019-11-20 14:02:09.806  - [32minfo[39m: host.ioBroker-Pi "system.adapter.wifilight-community.0" disabled
2019-11-20 14:02:09.807  - [32minfo[39m: host.ioBroker-Pi stopInstance system.adapter.wifilight-community.0 (force=false, process=true)
2019-11-20 14:02:09.812  - [32minfo[39m: host.ioBroker-Pi stopInstance system.adapter.wifilight-community.0 send kill signal
2019-11-20 14:02:09.814  - [32minfo[39m: wifilight-community.0 (3677) Got terminate signal TERMINATE_YOURSELF
2019-11-20 14:02:10.060  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]: TypeError: Cannot read property '0' of undefined
2019-11-20 14:02:10.061  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at dcs (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:304:33)
2019-11-20 14:02:10.062  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at CDevice.getFullId (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1113:20)
2019-11-20 14:02:10.062  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at WifiLight.createDevice (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:197:19)
2019-11-20 14:02:10.062  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at WifiLight.run (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:170:10)
2019-11-20 14:02:10.063  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at main (/opt/iobroker/node_modules/iobroker.wifilight-community/main.js:917:54)
2019-11-20 14:02:10.063  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:1297:9
2019-11-20 14:02:10.063  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at safeCallback (/opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:188:13)
2019-11-20 14:02:10.064  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at /opt/iobroker/node_modules/iobroker.wifilight-community/node_modules/soef/soef.js:848:21
2019-11-20 14:02:10.064  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at objects.getObjectView (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:3499:25)
2019-11-20 14:02:10.064  - [31merror[39m: host.ioBroker-Pi Caught by controller[0]:     at client.evalsha (/opt/iobroker/node_modules/iobroker.js-controller/lib/objects/objectsInRedis.js:2243:17)
2019-11-20 14:02:10.065  - [32minfo[39m: host.ioBroker-Pi instance system.adapter.wifilight-community.0 terminated with code 0 (NO_ERROR)`
